version: '3'
      
services:

  postgres:
    build:
      context: ./forDatabaseDeploy
      dockerfile: Dockerfile
    volumes:
      - "/home/theeska/postgres/:/var/lib/postgresql/ "
    expose:
      - "5432"

  go:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    depends_on:
      - postgres
    environment:
      - DATABASE_IP=postgres
